### PR TITLE
Maven dependencies

### PR DESCRIPTION
**Pull request by baulea**
# Upgrade the libraries and make it compatible with Java8 

PR Branch
**_[here](https://github.com/baulea/zerocode/tree/maven_dependencies)_**

## Motivation and Context
upgrade multiple maven dependencies for later Java17 compatibility
#607 

## Checklist:

* [ ] Unit tests added

* [ ] Integration tests added

* [x] Test names are meaningful

* [x] Feature manually tested

* [x] Branch build passed

* [x] No 'package.*' in the imports

* [ ] Relevant Wiki page updated with clear instruction for the end user
  * [x] Not applicable. This was only a refactor change, no functional or behaviour changes were introduced

* [ ] Http test added to `http-testing` module(if applicable) ?
  * [x] Not applicable. The changes did not affect HTTP automation flow

* [ ] Kafka test added to `kafka-testing` module(if applicable) ?
  * [x] Not applicable. The changes did not affect Kafka automation flow

* [x] Manually tested the Reports generated and all tabs have visual metrics as earlier?

### CODE REVIEW

**Comment by nirmalchandra** [comment]
Overall looking great @baulea .

Any specific reason you updated from `ExtentHtmlReporter` to `ExtentSparkReporter` ? 
Is this `ExtentHtmlReporter` deprecated?

**Comment by authorjapps** [comment]
Thanks for the great work getting this PR raised.

Was manually testing some aspects such as reports etc to ensure it's not breaking the existing projects.

Will perform few more checks soon and then merge 👍

**Comment by baulea** [comment]
@nirmalchandra Thank you for reviewing the changes! I updated from ExtentHtmlReporter to ExtentSparkReporter, because ExtentHtmlReporter  has been removed in version 5 of com.aventstack:extentreports https://stackoverflow.com/questions/66422304/extenthtmlreporter-class-cant-be-imported-with-extentreports-5-0-6-version

**Comment by a1shadows** [comment]
@baulea  Hey, do you think it is possible for us to a scan on the project to check if any other dependencies can be upgraded? One way to do this would be to analyze all the dependencies that have security vulnerabilities and corresponding fixes in a recent version.

An IDE can be used to do this. On IntelliJ, when I `Right Click + Analyze + Show Vulnerable Dependencies` I get a report of all vulnerable dependencies. 

I've attached a screenshot of analysis that I ran on your branch. Maybe we can use this as a reference
Screenshot 2024-02-20 at 16 58 15

**Comment by authorjapps** [comment]
This PR pretty much updates to latest versions of the most dependencies.
We should be fine for now.

**Review by authorjapps — APPROVED** [review]

**Pull request merged**
