### PR TITLE
ISSUE-598 # remove maven-compiler warnings with target Java 17 (JDK8 Compatible)

### PR DESCRIPTION
**Pull request by baulea**
# remove maven-compiler warnings with target Java 17 (JDK8 Compatible)

PR Branch
**_[pull request](https://github.com/baulea/zerocode/tree/java17)_**

## Motivation and Context
#598 

## Checklist:

* [ ] Unit tests added

* [ ] Integration tests added

* [ ] Test names are meaningful

* [x] Feature manually tested

* [x] Branch build passed

* [x] No 'package.*' in the imports

* [ ] Relevant Wiki page updated with clear instruction for the end user
  * [x] Not applicable. This was only a refactor change, no functional or behaviour changes were introduced

* [ ] Http test added to `http-testing` module(if applicable) ?
  * [x] Not applicable. The changes did not affect HTTP automation flow

* [ ] Kafka test added to `kafka-testing` module(if applicable) ?
  * [x] Not applicable. The changes did not affect Kafka automation flow

### CODE REVIEW

**Comment by baulea** [comment]
@authorjapps @nirmalchandra This PR could be merged into master. It is fully compatible with JDK8.

**Comment by authorjapps** [comment]
CI Passed 🟢  as on : `[INFO] Finished at: 2024-02-27T16:17:34Z`

**Review by authorjapps — APPROVED** [review]

**Comment by nirmalchandra** [comment]
@baulea , just checking why this PR name has "Java 17" ?

**Comment by nirmalchandra** [comment]
I am slightly late, already merged :-)

**Pull request merged**
