### PR TITLE
[Issue #207] Implementing Feature : Meta Data section (Scenario JSON)

### PR DESCRIPTION
**Pull request by prayascoriolis**
# <Feature Title>
WIP: [Issue #207 ] Implementing feature: Meta Data section in Scenario Json

## Fixes Issue
- [x] Which issue or ticket was(will be) fixed by this PR? (207)

PR Branch
**https://github.com/prayascoriolis/zerocode/tree/ISSUE-207-Meta-Data-Section**

## Motivation and Context

- So far, I've completed following changes:

1. Implemented the **unit test case** associated with the issue which includes a **java test file** in http-testing and an **assertions json file** in resources which contains the meta data.
2. **Updated ScenarioSpec.java** to include a meta field of type Map<String, List>.
3. **Modified ZeroCodeCsvReport.java** to add new fields: metaAuthors, metaTickets, metaCategories, and metaOthers.
4. **Updated ZeroCodeCsvReportBuilder.java** to include builder methods for the new meta data fields.
5. **For ZeroCodeExecResult.java:** Added a new field private Map<String, List<String>> meta; and corresponding getter/setter methods to store and retrieve meta data for each execution result.
6. **ZeroCodeReportGeneratorImpl.java**: added logic to include meta data in the Extent report generation, CSV schema, and CSV row building processes, ensuring meta information is captured in both HTML and CSV reports.

## Checklist:

* [x] New Unit tests were added

* [x] Integration tests were added

* [x] Test names are meaningful

* [x] Feature manually tested and outcome is successful

* [x] PR doesn't break any of the earlier features for end users

* [x] Branch build passed in CI

* [x] No 'package.*' in the imports

* [x] Relevant DOcumentation page added or updated with clear instructions and examples for the end user

  * [x] Not applicable. The changes did not affect HTTP automation flow

  * [x] Not applicable. The changes did not affect Kafka automation flow

### CODE REVIEW

**Comment by nirmalchandra** [comment]
resources

@prayascoriolis, can you make these two lower case letters?
_(just to be consistent with other folders and files)_

**Comment by prayascoriolis** [comment]
> resources
> @prayascoriolis, can you make these two lower case letters? _(just to be consistent with other folders and files)_

@nirmalchandra thankyou, i made those changes.

**Comment by nirmalchandra** [comment]
Looks like you're unsure about naming conventions for Java.

Try to have a look here:
https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html

- Then please correct the below class name and anyother things you're trying to modify.

We won't be able to approve or merge the PR till then.

- - - -

http-testingsrctest

**Comment by prayascoriolis** [comment]
> Looks like you're unsure about naming conventions for Java.
> 
> Try to have a look here: https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html
> 
> * Then please correct the below class name and anyother things you're trying to modify.
> 
> We won't be able to approve or merge the PR till then.
> 
> http-testingsrctest

Thanks, I fixed the class name and resubmitted the PR.

**Review by omkar-shitole — APPROVED** [review]

**Pull request merged**
