### PR TITLE
ISSUE-601 # Resolve JSON.CONTENT as object or array

### PR DESCRIPTION
**Pull request by vivektiwary**
Fixes Issue: https://github.com/authorjapps/zerocode/issues/601

# <Feature Title>

PR Branch
**_#ADD LINK TO THE PR BRANCH_**

## Checklist:

* [x] Unit tests added

* [x] Integration tests added

* [x] Test names are meaningful

* [x] Feature manually tested

* [x] Branch build passed

* [x] No 'package.*' in the imports

* [ ] Relevant Wiki page updated with clear instruction for the end user
  * [ ] Not applicable. This was only a refactor change, no functional or behaviour changes were introduced

* [x] Http test added to `http-testing` module(if applicable) ?
  * [ ] Not applicable. The changes did not affect HTTP automation flow

* [ ] Kafka test added to `kafka-testing` module(if applicable) ?
  * [x] Not applicable. The changes did not affect Kafka automation flow

### CODE REVIEW

**Comment by authorjapps** [comment]
Hello @vivektiwary , Hope you're well. Thanks for the PR. Looking great from impl point of view.

Can you please take care of a few more things in the PR?


1
===
Can you please add some tests as I couldn't find any in the PR ?
You can look and follow the tests how they are written for `"JSON.FILE:"`.
Please add:
a) Unit tests (top priority)
b) Integration tests (next priority)


2
===
Once added, please tick the following checkboxes encircled.
image

**Comment by vivektiwary** [comment]
Hi,
I opened it as a draft for my reference. I am adding the test cases as
well. I will remove the draft status after adding the tests.

Thank you
Vivek

**Comment by vivektiwary** [comment]
I have added a few Unit test cases, working on some more. Then I will add the integration test cases as well.

**Comment by authorjapps** [comment]
> I have added a few Unit test cases, working on some more. Then I will add the integration test cases as well.

Sounds great.
Just have a watch on the "Checks" tab for CI status after your commits.
CI Link: https://github.com/authorjapps/zerocode/pull/612/checks

**Comment by vivektiwary** [comment]
@authorjapps this PR is now ready for review.

**Comment by authorjapps** [comment]
@vivektiwary , can you look at the build failures and get them fixed?
Thanks in advance

**Pull request merged**
