### PR TITLE
ISSUES-603 Secrets not logged but used for API executions

### PR DESCRIPTION
**Pull request by nirmalchandra**
Ticket #603 

# <Feature Title>

PR Branch
**_#ADD LINK TO THE PR BRANCH_**

## Checklist:

* [x] Unit tests added

* [x] Integration tests added

* [x] Test names are meaningful

* [x] Feature manually tested

* [x] Branch build passed

* [x] No 'package.*' in the imports

* [ ] Relevant Wiki page updated with clear instruction for the end user
  * [ ] Not applicable. This was only a refactor change, no functional or behaviour changes were introduced

* [ ] Http test added to `http-testing` module(if applicable) ?
  * [ ] Not applicable. The changes did not affect HTTP automation flow

* [ ] Kafka test added to `kafka-testing` module(if applicable) ?
  * [x] Not applicable. The changes did not affect Kafka automation flow

### CODE REVIEW

**Comment by nirmalchandra** [comment]
Needs Unit test coverage now, for these two methods:
- getMaskedTokensReplaced
- getMaskedTokensRemoved

@DohaRamadan FYA, when you're ready please add.

**Comment by DohaRamadan** [comment]
> Needs Unit test coverage now, for these two methods:
> 
> * getMaskedTokensReplaced
> * getMaskedTokensRemoved
> 
> @DohaRamadan FYA, when you're ready please add.

i added it here #620 
if you have any thing i can contribute to, im more than happy to help!

**Comment by nirmalchandra** [comment]
> > Needs Unit test coverage now, for these two methods:
> > 
> > * getMaskedTokensReplaced
> > * getMaskedTokensRemoved
> > 
> > @DohaRamadan FYA, when you're ready please add.
> 
> i added it here #620 if you have any thing i can contribute to, im more than happy to help!

Thank you,
Also now I have pushed the remaining bit of framework code.

Next, you can add few integration tests:
Folder: `...src/test/resources/integration_test_files` .
Creata a new dir e.g. : `masked`.
Then add a scenario file in this folder with `"${MASKED:pass123etc...}" ` used in the request section. 
_(To do this try to mimic other integration tests from another folder(s))_

Outcome:
- Test should pass
- Console log should print `"***masked***"`

**Comment by DohaRamadan** [comment]
> > > Needs Unit test coverage now, for these two methods:
> > > 
> > > * getMaskedTokensReplaced
> > > * getMaskedTokensRemoved
> > > 
> > > @DohaRamadan FYA, when you're ready please add.
> > 
> > 
> > i added it here #620 if you have any thing i can contribute to, im more than happy to help!
> 
> Thank you, Also now I have pushed the remaining bit of framework code.
> 
> Next, you can add few integration tests: Folder: `...src/test/resources/integration_test_files` . Creata a new dir e.g. : `masked`. Then add a scenario file in this folder with `"${MASKED:pass123etc...}" ` used in the request section. _(To do this try to mimic other integration tests from another folder(s))_
> 
> Outcome:
> 
> * Test should pass
> * Console log should print `"***masked***"`

I wrote some initial tests but i am not able to run it or any integration tests, i always get the error message `0 test classes found in package `  Is there specific steps i need to follow to run the integration tests?

**Comment by authorjapps** [comment]
> I wrote some initial tests but i am not able to run it or any integration tests, i always get the error message 0 test classes found in package  Is there specific steps i need to follow to run the integration tests?

Hello, Thanks.
Please try to run the below scenario locally from your laptop. Once it PASSED, you can mimic the same behaviour.

.../core/src/test/java/org/jsmart/zerocode/integrationtests/HelloWorldInMemoryTest.java

(this one using the file `"get_api_integration_test.json"` from folder `".../core/src/test/resources/integration_test_files/helloworld/"`)

**Comment by DohaRamadan** [comment]
> > I wrote some initial tests but i am not able to run it or any integration tests, i always get the error message 0 test classes found in package  Is there specific steps i need to follow to run the integration tests?
> 
> Hello, Thanks. Please try to run the below scenario locally from your laptop. Once it PASSED, you can mimic the same behaviour.
> 
> .../core/src/test/java/org/jsmart/zerocode/integrationtests/HelloWorldInMemoryTest.java
> 
> (this one using the file `"get_api_integration_test.json"` from folder `".../core/src/test/resources/integration_test_files/helloworld/"`)

when i try to run the HelloWorldInMemoryTest.java i get this error 
``` com.google.common.util.concurrent.ExecutionError: java.lang.ExceptionInInitializerError

	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2216)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4147)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4151)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5140)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5146)
	at com.google.inject.internal.FailableCache.get(FailableCache.java:48)
	at com.google.inject.internal.ConstructorInjectorStore.get(ConstructorInjectorStore.java:50)
	at com.google.inject.internal.ConstructorBindingImpl.initialize(ConstructorBindingImpl.java:136)
	at com.google.inject.internal.InjectorImpl.initializeJitBinding(InjectorImpl.java:547)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:884)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:805)
	at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:282)
	at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:214)
	at com.google.inject.internal.InjectorImpl.getInternalFactory(InjectorImpl.java:890)
	at com.google.inject.internal.FactoryProxy.notify(FactoryProxy.java:46)
	at com.google.inject.internal.ProcessedBindingData.runCreationListeners(ProcessedBindingData.java:50)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:134)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at org.jsmart.zerocode.core.runner.ZeroCodeUnitRunner.getMainModuleInjector(ZeroCodeUnitRunner.java:162)
	at org.jsmart.zerocode.core.runner.ZeroCodeUnitRunner.getInjectedSmartUtilsClass(ZeroCodeUnitRunner.java:201)
	at org.jsmart.zerocode.core.runner.ZeroCodeUnitRunner.<init>(ZeroCodeUnitRunner.java:80)
	at org.jsmart.zerocode.core.tests.customrunner.TestOnlyZeroCodeUnitRunner.<init>(TestOnlyZeroCodeUnitRunner.java:25)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:50)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
Caused by: java.lang.ExceptionInInitializerError
	at com.google.inject.internal.cglib.reflect.$FastClassEmitter.<init>(FastClassEmitter.java:67)
	at com.google.inject.internal.cglib.reflect.$FastClass$Generator.generateClass(FastClass.java:72)
	at com.google.inject.internal.cglib.core.$DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
	at com.google.inject.internal.cglib.core.$AbstractClassGenerator.create(AbstractClassGenerator.java:216)
	at com.google.inject.internal.cglib.reflect.$FastClass$Generator.create(FastClass.java:64)
	at com.google.inject.internal.BytecodeGen.newFastClass(BytecodeGen.java:204)
	at com.google.inject.internal.DefaultConstructionProxyFactory.create(DefaultConstructionProxyFactory.java:54)
	at com.google.inject.internal.ProxyFactory.create(ProxyFactory.java:159)
	at com.google.inject.internal.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:90)
	at com.google.inject.internal.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:29)
	at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:37)
	at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:33)
	at com.google.inject.internal.FailableCache$1.load(FailableCache.java:37)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3708)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2416)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2299)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2212)
	... 39 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @26f0a63f
	at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:391)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:367)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:315)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:203)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:197)
	at com.google.inject.internal.cglib.core.$ReflectUtils$2.run(ReflectUtils.java:56)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
	at com.google.inject.internal.cglib.core.$ReflectUtils.<clinit>(ReflectUtils.java:46)
	... 56 more
```

**Comment by DohaRamadan** [comment]
> > I wrote some initial tests but i am not able to run it or any integration tests, i always get the error message 0 test classes found in package  Is there specific steps i need to follow to run the integration tests?
> 
> Hello, Thanks. Please try to run the below scenario locally from your laptop. Once it PASSED, you can mimic the same behaviour.
> 
> .../core/src/test/java/org/jsmart/zerocode/integrationtests/HelloWorldInMemoryTest.java
> 
> (this one using the file `"get_api_integration_test.json"` from folder `".../core/src/test/resources/integration_test_files/helloworld/"`)

what URL should i use in the json scenario?

**Comment by authorjapps** [comment]
> > > I wrote some initial tests but i am not able to run it or any integration tests, i always get the error message 0 test classes found in package  Is there specific steps i need to follow to run the integration tests?
> > 
> > 
> > Hello, Thanks. Please try to run the below scenario locally from your laptop. Once it PASSED, you can mimic the same behaviour.
> > .../core/src/test/java/org/jsmart/zerocode/integrationtests/HelloWorldInMemoryTest.java
> > (this one using the file `"get_api_integration_test.json"` from folder `".../core/src/test/resources/integration_test_files/helloworld/"`)
> 
> what URL should i use in the json scenario?

To start with, you can use the same URL even in your new scenario too. 
I think you can treat one of the field as a password field for the same of testing the feature, even if the "key" name is different, it should not matter imo.

**Comment by DohaRamadan** [comment]
> > > > I wrote some initial tests but i am not able to run it or any integration tests, i always get the error message 0 test classes found in package  Is there specific steps i need to follow to run the integration tests?
> > > 
> > > 
> > > Hello, Thanks. Please try to run the below scenario locally from your laptop. Once it PASSED, you can mimic the same behaviour.
> > > .../core/src/test/java/org/jsmart/zerocode/integrationtests/HelloWorldInMemoryTest.java
> > > (this one using the file `"get_api_integration_test.json"` from folder `".../core/src/test/resources/integration_test_files/helloworld/"`)
> > 
> > 
> > what URL should i use in the json scenario?
> 
> To start with, you can use the same URL even in your new scenario too. I think you can treat one of the field as a password field for the sake of testing the feature, even if the "key" name is different, it should not matter IMO.

 The /api/v1/search/persons endpoint has 2 query parameters lang and city which has to be Amazing and Lon respectfully, I don't know where the ${MASKED:str} would fit in this scenario, Also, I noticed that the getMaskedTokensReplaced function is not called anywhere in the code, so how exactly is it working?

**Comment by nirmalchandra** [comment]
> > > > > I wrote some initial tests but i am not able to run it or any integration tests, i always get the error message 0 test classes found in package  Is there specific steps i need to follow to run the integration tests?
> > > > 
> > > > 
> > > > Hello, Thanks. Please try to run the below scenario locally from your laptop. Once it PASSED, you can mimic the same behaviour.
> > > > .../core/src/test/java/org/jsmart/zerocode/integrationtests/HelloWorldInMemoryTest.java
> > > > (this one using the file `"get_api_integration_test.json"` from folder `".../core/src/test/resources/integration_test_files/helloworld/"`)
> > > 
> > > 
> > > what URL should i use in the json scenario?
> > 
> > 
> > To start with, you can use the same URL even in your new scenario too. I think you can treat one of the field as a password field for the sake of testing the feature, even if the "key" name is different, it should not matter IMO.
> 
> The /api/v1/search/persons endpoint has 2 query parameters lang and city which has to be Amazing and Lon respectfully, I don't know where the ${MASKED:str} would fit in this scenario, Also, I noticed that the getMaskedTokensReplaced function is not called anywhere in the code, so how exactly is it working?

Ok.
`getMaskedTokensReplaced` is called from `ZeroCodeMultiStepsScenarioRunnerImpl` for now and other places(wip).
For now I have pushed a vanila test scenario to prove the functionality works.

Will add couple of more scenarios soon and any additional code needed.

**Review by authorjapps — APPROVED** [review]

**Pull request merged**
