### PR TITLE
logging changes

### PR DESCRIPTION
**Pull request by IshaJ721**
# <Feature Title>

PR Branch
**_#ADD LINK TO THE PR BRANCH_**

## Checklist:

* [ ] Unit tests added

* [ ] Integration tests added

* [ ] Test names are meaningful

* [ ] Feature manually tested

* [ ] Branch build passed

* [ ] No 'package.*' in the imports

* [ ] Relevant Wiki page updated with clear instruction for the end user
  * [ ] Not applicable. This was only a refactor change, no functional or behaviour changes were introduced

* [ ] Http test added to `http-testing` module(if applicable) ?
  * [ ] Not applicable. The changes did not affect HTTP automation flow

* [ ] Kafka test added to `kafka-testing` module(if applicable) ?
  * [ ] Not applicable. The changes did not affect Kafka automation flow

### CODE REVIEW

**Comment by authorjapps** [comment]
Thanks @IshaJ721 ,
Looks like there is 1 error in the PR. See screenshots beelow. Can you please fix this please?

CI Build Link:
https://github.com/authorjapps/zerocode/actions/runs/5365766051/jobs/9740988963

image

**Comment by IshaJ721** [comment]
> Thanks @IshaJ721 , Looks like there is 1 error in the PR. See screenshots beelow. Can you please fix this please?
> 
> CI Build Link: https://github.com/authorjapps/zerocode/actions/runs/5365766051/jobs/9740988963
> 
> image

A fix for this was pushed into the logging branch more than a week ago. I replaced error() with warning(). Can you rebuild?

**Review by M3lkior — APPROVED** [review]
Nice! Thanks for the PR ! Can you just reword your commit message following the conventional commits conventions ? https://www.conventionalcommits.org/en/v1.0.0/

**Comment by IshaJ721** [comment]
I built using intelliJ and the log is below.
There are no errors as shown in the intelliJ log below...

Clearing build system data...
Executing pre-compile tasks...
Cleaning output directories…
Running 'before' tasks
Checking sources
Copying resources... [zerocode-tdd-jupiter]
Copying resources... [zerocode-tdd]
Copying resources... [zerocode-maven-archetype]
Copying resources... [kafka-testing]
Copying resources... [http-testing]
Parsing java… [zerocode-tdd]
java: source value 8 is obsolete and will be removed in a future release
java: target value 8 is obsolete and will be removed in a future release
java: To suppress warnings about obsolete options, use -Xlint:-options.
Writing classes… [zerocode-tdd]
Updating dependency information… [zerocode-tdd]
Adding nullability assertions… [zerocode-tdd]
Adding threading assertions… [zerocode-tdd]
Adding pattern assertions… [zerocode-tdd]
Parsing java… [tests of zerocode-tdd]
Writing classes… [tests of zerocode-tdd]
Updating dependency information… [tests of zerocode-tdd]
Adding nullability assertions… [tests of zerocode-tdd]
Adding threading assertions… [tests of zerocode-tdd]
Adding pattern assertions… [tests of zerocode-tdd]
Parsing java… [zerocode-tdd-jupiter]
Writing classes… [zerocode-tdd-jupiter]
Updating dependency information… [zerocode-tdd-jupiter]
Adding nullability assertions… [zerocode-tdd-jupiter]
Adding threading assertions… [zerocode-tdd-jupiter]
Adding pattern assertions… [zerocode-tdd-jupiter]
Parsing java… [tests of zerocode-tdd-jupiter]
Writing classes… [tests of zerocode-tdd-jupiter]
Updating dependency information… [tests of zerocode-tdd-jupiter]
Adding nullability assertions… [tests of zerocode-tdd-jupiter]
Adding threading assertions… [tests of zerocode-tdd-jupiter]
Adding pattern assertions… [tests of zerocode-tdd-jupiter]
Parsing java… [kafka-testing]
Writing classes… [kafka-testing]
Updating dependency information… [kafka-testing]
Adding nullability assertions… [kafka-testing]
Adding threading assertions… [kafka-testing]
Adding pattern assertions… [kafka-testing]
Parsing java… [tests of kafka-testing]
Writing classes… [tests of kafka-testing]
Updating dependency information… [tests of kafka-testing]
Adding nullability assertions… [tests of kafka-testing]
Adding threading assertions… [tests of kafka-testing]
Adding pattern assertions… [tests of kafka-testing]
Parsing java… [http-testing]
Writing classes… [http-testing]
Updating dependency information… [http-testing]
Adding nullability assertions… [http-testing]
Adding threading assertions… [http-testing]
Adding pattern assertions… [http-testing]
Parsing java… [tests of http-testing]
Writing classes… [tests of http-testing]
Updating dependency information… [tests of http-testing]
Adding nullability assertions… [tests of http-testing]
Adding threading assertions… [tests of http-testing]
Adding pattern assertions… [tests of http-testing]
Running 'after' tasks
javac 20.0.1 was used to compile java sources
Finished, saving caches…
Executing post-compile tasks...
Finished, saving caches…
Synchronizing output directories...
7/8/2023 6:41 PM - Build completed successfully with 180 warnings in 1 min, 10 sec

**Comment by nirmalchandra** [comment]
Hello All, I am making some minor changes to the PR to make it better.
e.g. the following:
- Remove the "id=null" printing in the log/console
- Some INFO level --> updating to WARN, as few dependent libs printing lot of debug-info/noise at INFO level
- Some WARN level --> updating to INFO or DEBUG etc
- Trying to run few Kafka and Multi-step tests so see everything hanging together as expected in the log
- etc

**Pull request merged**
