### PR TITLE
Upgrading Jackson, Guice, Guava and jsonassert

### LINKED ISSUE #607: Upgrade the libraries and make it compatible with Java8
AC:
Upgrade the dependant libraries to their latest compatible version with Java8.

This seems like a pre-req or a good excersize before switching to Java17.

- - - - 
Some work already has been done by @baulea .

Hello @baulea , can you please put the ticket/issue details and PR details in the comments for everyone's visibility?

### PR DESCRIPTION
**Pull request by a1shadows**
# <Feature Title>

## Fixes Issue
- [ ] Which issue or ticket was(will be) fixed in this PR?
partially fixes #607 
resolves #642 

PR Branch
**_#ADD LINK TO THE PR BRANCH_**

## Motivation and Context

Notable changes include 

1. adding null checks to JsonNodes because recent Jackson versions deserialize null values to Java null instead of Jackson NullNode
2. Moving from javax.inject to jakarta.inject with latest Guice version

## Checklist:

* [ ] Unit tests added

* [ ] Integration tests added

* [ ] Test names are meaningful

* [ ] Feature manually tested

* [ ] Branch build passed

* [ ] No 'package.*' in the imports

* [ ] Relevant Wiki page updated with clear instruction for the end user
  * [ ] Not applicable. This was only a refactor change, no functional or behaviour changes were introduced

* [ ] Http test added to `http-testing` module(if applicable) ?
  * [ ] Not applicable. The changes did not affect HTTP automation flow

* [ ] Kafka test added to `kafka-testing` module(if applicable) ?
  * [ ] Not applicable. The changes did not affect Kafka automation flow

### CODE REVIEW

**Comment by a1shadows** [comment]
@authorjapps  Can you review this? There are a lot of small changes with this upgrade

**Comment by baulea** [comment]
@a1shadows With https://github.com/authorjapps/zerocode/pull/638 junit was upgraded from 4.12 to 4.13.2. This recent PR https://github.com/authorjapps/zerocode/pull/641 contains a downgrade to 4.12 again. Would you please change that?

**Comment by a1shadows** [comment]
> @a1shadows With #638 junit was upgraded from 4.12 to 4.13.2. This recent PR #641 contains a downgrade to 4.12 again. Would you please change that?

@baulea Done

**Review by authorjapps — APPROVED** [review]
Looks Good. CI also Green 🟢

**Pull request merged**
