### PR TITLE
Fixed flaky test-case: ConsumerJsonRecordTest.should_serialize_a_record_with_headers

### PR DESCRIPTION
**Pull request by hermya**
# Fixed flaky test-case

## Fixes Issue
- [x] Which issue or ticket was(will be) fixed by this PR? 
authorjapps/zerocode/issues/685

PR Branch
**[fork](https://github.com/hermya/zerocode)**

## Motivation and Context
ConsumerJsonRecordTest.should_serialize_a_record_with_headers is a flaky test, fixed in this PR.

POINT OF FAILURE -> random attribute ordering in hashmap
Fixed using NonDex pugin
Suggested command to check all flaky tests :
> mvn nondex:nondex

For particular test:
Add the following lines to your pom.xml
```
  <plugin> <!-- for flaky testing -->
      <groupId>edu.illinois</groupId>
      <artifactId>nondex-maven-plugin</artifactId>
      <version>2.1.7</version>
  </plugin>
```
and run
>mvn -pl ./core nondex:nondex -Dtest=org.jsmart.zerocode.core.kafka.receive.message.ConsumerJsonRecordTest#should_serialize_a_record_with_headers -DnondexRuns=10

**OR**

>mvn -pl ./core edu.illinois:nondex-maven-plugin:2.1.7:nondex -Dtest=org.jsmart.zerocode.core.kafka.receive.message.ConsumerJsonRecordTest#should_serialize_a_record_with_headers -DnondexRuns=10

For more information : https://github.com/TestingResearchIllinois/NonDex

## Checklist:

* [ ] New Unit tests were added
  * [ ] Covered in existing Unit tests

* [ ] Integration tests were added
  * [ ] Covered in existing Integration tests

* [ ] Test names are meaningful

* [ ] Feature manually tested and outcome is successful

* [X] PR doesn't break any of the earlier features for end users
  * [ ] WARNING! This might break one or more earlier earlier features, hence left a comment tagging all reviewrs

* [X] Branch build passed in CI

* [X] No 'package.*' in the imports

* [ ] Relevant DOcumentation page added or updated with clear instructions and examples for the end user
  * [X] Not applicable. This was only a code refactor change, no functional or behaviourial changes were introduced

* [ ] Http test added to `http-testing` module(if applicable) ?
  * [X] Not applicable. The changes did not affect HTTP automation flow

* [ ] Kafka test added to `kafka-testing` module(if applicable) ?
  * [X] Not applicable. The changes did not affect Kafka automation flow

### CODE REVIEW

**Comment by nirmalchandra** [comment]
@hermya , appreciate the fix. Can you create a Issue(short, one or two lines in fine) and link to this ticket please?

We'll have a look soon

**Comment by hermya** [comment]
@nirmalchandra, thank you! Created an issue and updated it in above comment as well.
For your ref: authorjapps/zerocode/issues/685

**Comment by nirmalchandra** [comment]
> @nirmalchandra, thank you! Created an issue and updated it in the above comment as well. For your ref: [/issues/685](https://github.com/authorjapps/zerocode/issues/685)

Thank you @hermya , can you please put couple of line about the fix (how the test was fixed) ?
Also, please explain how it was never failed during the CI build earlier?
Is it failing in your local laptop (sometimes?) ?

In the mean time I will get the CI triggered(as soon as we see the details I mean).

**Comment by hermya** [comment]
You're welcome @nirmalchandra !

### 1. Can you please put couple of line about the fix (how the test was fixed)?
In HashMap implementation of Map, there's no guarantee of key ordering. LinkedHashMap keeps the order of insertion and it's toString() or keySet() will also maintain that order, ensuring deterministic representation.<br>
### 2. Please explain how it was never failed during the CI build earlier: 
It might have never failed because the hash-key ordering is dependent on the current state of underlying jvm. It is possible that it fails on a different environment<br>
### 3. Is it failing in your local laptop (sometimes?) ? 
It fails with the nondex. Nondex is a useful tool for such situations, where outputs of non-deterministic states are compared.<br>
### 4. But was the maven dependency which you added&removed from the POM file, was pushed by mistake?
I added it earlier, thinking that it'd be a good idea for your experimentation. However, you can run nondex without it using slightly modified command mentioned in main comment, so I removed it for cleanliness.

**Review by nirmalchandra — APPROVED** [review]

**Pull request merged**
