### PR TITLE
ISSUE-581 # preliminary work for Java 17 support - updating maven dependencies

### PR DESCRIPTION
**Pull request by baulea**
# ISSUE-581 # preliminary work for Java 17 support - updating maven dependencies

PR Branch
**_https://github.com/baulea/zerocode/tree/feature/java17_**

## Motivation and Context
Updated maven dependencies to versions that are more up-to-date. This is preliminary work for Java 17 support. I'll continue with work for Java 17 support.

"mvn clean install" succeeded with all tests

## Checklist:

* [ ] Unit tests added

* [ ] Integration tests added

* [ ] Test names are meaningful

* [x] Feature manually tested

* [x] Branch build passed

* [x] No 'package.*' in the imports

* [x] Relevant Wiki page updated with clear instruction for the end user
  * [x] Not applicable. This was only a refactor change, no functional or behaviour changes were introduced

* [x] Http test added to `http-testing` module(if applicable) ?
  * [x] Not applicable. The changes did not affect HTTP automation flow

* [x] Kafka test added to `kafka-testing` module(if applicable) ?
  * [x] Not applicable. The changes did not affect Kafka automation flow

### CODE REVIEW

**Comment by baulea** [comment]
With JDK17 I didn't get a successful maven build with the current authorjapps:master branch. I thought it a good idea -- instead of debugging problems -- to start with updating a bunch of maven dependencies - e.g. a guice version >=5.1.0 is needed for Java17 support (https://github.com/google/guice/wiki/Guice510). And so this pull request was born.

Should I break up this pull request into smaller chunks and create a separate issue and pull request for each chunk? Or are you generally cautious about updating maven dependencies and we should keep our hands off?

**Comment by baulea** [comment]
I'll better break this into smaller chunks and create issues for each one.

**Comment by authorjapps** [comment]
> With JDK17 I didn't get a successful maven build with the current authorjapps:master branch. I thought it a good idea -- instead of debugging problems -- to start with updating a bunch of maven dependencies - e.g. a guice version >=5.1.0 is needed for Java17 support (https://github.com/google/guice/wiki/Guice510). And so this pull request was born.
> 
> Should I break up this pull request into smaller chunks and create a separate issue and pull request for each chunk? Or are you generally cautious about updating maven dependencies and we should keep our hands off?

Hello @baulea , appreciate you were looking into this in terms of updating the dependenct libraries 1st.
But can you please make sure it hangs together well with JDK8 builds and it doesn't break anything.
Once this is assured, we can think of the next step for JDK17 support.

I think it's better to create a separate module(if possible) for JDK 17 migration related works.
But I am not sure even if that's possible or we need a completely separate project.

**Comment by baulea** [comment]
Thank you very much for your reply. And thanks for sharing the goal to support JDK17.
My current pull request on updating maven dependencies was a bit mixed-up indeed (and therefore I closed the pull request myself). I fixated on a successful maven build and that the provided tests ran successfully (with JDK8). I only had a slight glance at conflicting dependencies and it seemed ok, but I did not cross check these conflicts.
So I'll concentrate on filing smaller chunks of updates that are easier to check. Thank you for your patience :-)

**Pull request closed without merging**
