### PR TITLE
introduce JsonPathJacksonProvider

### PR DESCRIPTION
**Pull request by baulea**
# <Feature Title>

## Fixes Issue
- [x] Which issue or ticket was(will be) fixed in this PR?  https://github.com/authorjapps/zerocode/issues/648

PR Branch
https://github.com/baulea/zerocode/tree/jsonPathJacksonProvider

## Motivation and Context
Move to jackson json provider in JsonPath instead of jsonsmart. Jackson is already used in zerocode, and we can get rid of jsonsmart as another JSON processor.

## Checklist:

* [ ] Unit tests added

* [ ] Integration tests added

* [x] Test names are meaningful

* [x] Feature manually tested

* [ ] Branch build passed

* [x] No 'package.*' in the imports

* [ ] Relevant Wiki page updated with clear instruction for the end user
  * [x] Not applicable. This was only a refactor change, no functional or behaviour changes were introduced

* [ ] Http test added to `http-testing` module(if applicable) ?
  * [x] Not applicable. The changes did not affect HTTP automation flow

* [ ] Kafka test added to `kafka-testing` module(if applicable) ?
  * [x] Not applicable. The changes did not affect Kafka automation flow

### CODE REVIEW

**Comment by baulea** [comment]
Hello @a1shadows , would you please have a look at this PR?

**Comment by a1shadows** [comment]
@baulea  hey it looks like CI is breaking. Can you take a look?

**Review by a1shadows — APPROVED** [review]
CI has passed. LGTM

**Comment by baulea** [comment]
Hi @a1shadows ,
thank you for merging and closing.

I've been on vacation last week and didn't respond to your question regarding the broken CI test. On my local machine all tests had run successfully (mvn clean install in main directory) before creating the PR and I could not reproduce the problem with the broken test.

Could you image any reason, why sometimes the CI test on GitHub seems to fail, and the next CI test is successful again without changes to the codebase in between?

**Comment by a1shadows** [comment]
@baulea all the CI started succeeding after a pull from master. Not sure why the tests were failing before but the pull from master seemed to have fixed the issues

**Pull request merged**
