### PR TITLE
Iss 330 send headers while producing to kafka

### PR DESCRIPTION
**Pull request by Cyril-Edme**
# send headers while producing to kafka

PR Branch
https://github.com/Cyril-Edme/zerocode/tree/ISS-330-send-headers-while-producing-to-kafka

## Motivation and Context
We should be able to send some headers in our Kafka message. As well as the consumer should be able to assert on the received headers.

## Checklist:

* [x] Unit tests added

* [x] Integration tests added

* [x] Test names are meaningful

* [x] Feature manually tested

* [x] Branch build passed

* [x] No 'package.*' in the imports

* [ ] Relevant Wiki page updated with clear instruction for the end user
  * [ ] Not applicable. This was only a refactor change, no functional or behaviour changes were introduced

* [ ] Http test added to `http-testing` module(if applicable) ?
  * [x] Not applicable. The changes did not affect HTTP automation flow

* [x] Kafka test added to `kafka-testing` module(if applicable) ?
  * [ ] Not applicable. The changes did not affect Kafka automation flow

### CODE REVIEW

**Comment by authorjapps** [comment]
@Cyril-Edme , We are happy to merge this unless you are adding any more stuffs like any tidy up work or any more test coverage you might have missed.
Please give us a shout if not to be merged soon by this weekend!

I have declined the other PR which looks duplicate of this and already outdated due to duplicate code.

**Comment by Cyril-Edme** [comment]
@authorjapps thanks for your commit with the few fix (good to know for the next time). It's all good for me, about the partition that we discussed about in slack, it's another topic with it's own issue.

**Comment by authorjapps** [comment]
> @authorjapps thanks for your commit with the few fix (good to know for the next time). It's all good for me, about the partition that we discussed about in slack, it's another topic with it's own issue.

Sure, Let's address that next...

**Comment by authorjapps** [comment]
solves #330

**Pull request merged**
