### PR TITLE
fix(validators): support of Zerocode expressions and jsonpath

### LINKED ISSUE #436: [KAFKA]Cannot inject ZeroCode variables into Validators
Description:
===

## This is my usecase:
Details were already provided initially. Copy pasting it _again_
1. Consuming from Kafka multiple messages which are from different partitions.
2. Need to validate the ID field of each message consumed. This ID is Random.Number generated in a previous test (REST POST).
3. Trying to access this ID deterministically using validators and it is not working. 
Below is the validator being used. While consuming we are trying to validate the ID of the message consumed. 
```
{
  "name": "consume_from_test-topic",
      "url": "kafka-topic:test-topic",
      "operation": "consume",
      "request": {
        "consumerLocalConfigs": {
          "recordType": "JSON",
          "commitSync": false,
          "showRecordsConsumed": true,
          "maxNoOfRetryPollsOrTimeouts": 2    
        }
      },
"validators": [
			{
				"field": "$..journals[?(@.id==${$.send_valid_unique_identifiers.response.body.rawJournals.[0].id})]",
				"value": "${$.send_valid_unique_identifiers.response.body.rawJournals.[0].id}"
			}
]
}
```
## This is my actual request and actual response

Paste a sample or example here:
```JSON
Complete logs already attached, as previously requested.

```
## This is what I want to assert or validate

Paste a sample or example here:
```JSON
Need to validate the value of ID field of each message consumed. This ID is Random.UUID Number generated in a previous test (REST POST)
```

Further details:
===

@authorjapps  Scenario: 
1. Consuming from Kafka multiple messages which are from different partitions.
2. Need to validate the ID field of each message consumed. This ID is Random.Number generated in a previous test (REST POST).
3. Trying to access this ID deterministically using validators and it is not working. 
Below is the validator being used. While consuming we are trying to validate the ID of the message consumed. 
```
{
  "name": "consume_from_test-topic",
      "url": "kafka-topic:test-topic",
      "operation": "consume",
      "request": {
        "consumerLocalConfigs": {
          "recordType": "JSON",
          "commitSync": false,
          "showRecordsConsumed": true,
          "maxNoOfRetryPollsOrTimeouts": 2    
        }
      },
"validators": [
			{
				"field": "$..journals[?(@.id==${$.send_valid_unique_identifiers.response.body.rawJournals.[0].id})]",
				"value": "${$.send_valid_unique_identifiers.response.body.rawJournals.[0].id}"
			}
]
}

### PR DESCRIPTION
**Pull request by M3lkior**
Close #436

# <Feature Title>

PR Branch
**_#ADD LINK TO THE PR BRANCH_**

## Motivation and Context

See issue #436 discussions

## Checklist:

* [x] Unit tests added

* [ ] Integration tests added

* [x] Test names are meaningful

* [x] Feature manually tested

* [ ] Branch build passed

* [x] No 'package.*' in the imports

* [ ] Relevant Wiki page updated with clear instruction for the end user
  * [x] Not applicable. This was only a refactor change, no functional or behaviour changes were introduced

* [ ] Http test added to `http-testing` module(if applicable) ?
  * [x] Not applicable. The changes did not affect HTTP automation flow

* [x] Kafka test added to `kafka-testing` module(if applicable) ?
  * [ ] Not applicable. The changes did not affect Kafka automation flow

### CODE REVIEW

**Comment by authorjapps** [comment]
Hi, will pick this after the CI issue is resolved. It's in progress now and hopefully will be sorted soon.

**Comment by M3lkior** [comment]
hello @authorjapps ; ok let me know when your CI is fixed ; i will refactor this pr to correctly implement the feature

**Comment by authorjapps** [comment]
Hello @M3lkior, CI has been fixed and works fine now. 
You can have a look here. The [current build](https://github.com/authorjapps/zerocode/actions/runs/3322330907) is Green.

**Comment by authorjapps** [comment]
I suggest please take the latest pull from the master and rebase/merge your changes 1st before adding more changes. 
This way you can observe the CI status even at your patch/branch or forked master.
This is possible due to the recent CI fix which is helpful.

And I appreciate you have been picking and collaborating on some of the important issues people have raised 🙏 .

**Comment by M3lkior** [comment]
> I suggest please take the latest pull from the master and rebase/merge your changes 1st before adding more changes. This way you can observe the CI status even at your patch/branch or forked master. This is possible due to the recent CI fix which is helpful.
> 
> And I appreciate you have been picking and collaborating on some of the important issues people have raised 🙏 .

ok @authorjapps  i will do that !

i plan to work on this issue this end of week ! my pr will be ready soon ;)

**Comment by authorjapps** [comment]
After merge, if you could take care of [this](https://github.com/authorjapps/zerocode/issues/436#issuecomment-1298502324) please.

**Comment by M3lkior** [comment]
hi @authorjapps ; the continuous integration step is broken ?

**Comment by nirmalchandra** [comment]
> hi @authorjapps ; the continuous integration step is broken ?

Hi @M3lkior, CI looks fine and Green. Actually showing SUCCESS. See below.
image

This [build #14](https://github.com/authorjapps/zerocode/actions/runs/3345675225/jobs/5541497182) is linked to your last commit.

**Review by nirmalchandra — APPROVED** [review]

**Comment by authorjapps** [comment]
> hi @authorjapps ; the continuous integration step is broken ?

Hey, CI looks good I think. apologies for the delay, slightly struggling in terms of capacity due to my day job. But will get this sorted and released in couple of days. 
ETA: by this weekend

**Comment by M3lkior** [comment]
> build #14

yep but not the travis-ci step:
image

No worry; i can help you to maintain this repo and the release process if you want and if it is possible

**Comment by authorjapps** [comment]
> > build #14
> 
> 
> No worry; i can help you to maintain this repo and the release process if you want and if it is possible

Amazing, that'll be really helpful. At least for now, your contribution to the upcoming PR reviews will be really useful.
Let me check about the Maven release stuff load-sharing, will get back to you.

For Travis, yes, it's looking bit wierd. I have raised a ticket here: https://github.com/authorjapps/zerocode/issues/548 to be looked at.

**Comment by authorjapps** [comment]
Done.
Available in release `1.3.31`.
Thanks for your patience 🙏

**Pull request merged**
