### PR TITLE
ISSUE-488 # Allow Kafka receiver to natively read AVRO records

### LINKED ISSUE #488: [Kafka] Allow Json consume to natively read AVRO Message
# Context

For my organization project, i needed to produce and consume AVRO messages from  the Schema Registry so i develop a custom `KakfaClient` to produce the AVRO message.

Concerning the consumption, i detected after a debugging phase that the actual `KafkaReceiver` is almost able to treat an incoming AVRO message format  thanks to the `readJson` method

Here is the actual implementation 

```
            ConsumerJsonRecord jsonRecord = new ConsumerJsonRecord(thisRecord.key(), null, valueNode, headersMap);
```

Here is the code which allow parsing AVRO record 

```
            jsonRecords.add(new ConsumerJsonRecord(keyNode, null, valueNode, headersMap));

```
with `keyNode` 
```
            JsonNode keyNode = objectMapper.readTree(key.toString());

```

I can do a PR if this issue is accepted

### PR DESCRIPTION
**Pull request by M3lkior**
Close #488

# <Feature Title>

PR Branch
**_#ADD LINK TO THE PR BRANCH_**

## Checklist:

* [x] Unit tests added

* [x] Integration tests added

* [x] Test names are meaningful

* [x] Feature manually tested

* [x] Branch build passed

* [x] No 'package.*' in the imports

* [ ] Relevant Wiki page updated with clear instruction for the end user
  * [x] Not applicable. This was only a refactor change, no functional or behaviour changes were introduced

* [ ] Http test added to `http-testing` module(if applicable) ?
  * [x] Not applicable. The changes did not affect HTTP automation flow

* [x] Kafka test added to `kafka-testing` module(if applicable) ?
  * [ ] Not applicable. The changes did not affect Kafka automation flow

### CODE REVIEW

**Comment by authorjapps** [comment]
Thanks for the PR.
Just checked, `package-lock.json` has been pushed to the repo probably by mistake.
Please delete it when you get chance

>https://github.com/authorjapps/zerocode/blob/d17a02a14b8a989ef5a548ace25f644acf8f0a2c/package-lock.json

**Comment by authorjapps** [comment]
Can you please add an(or couple of) integration tests ?
That will help all reviewers to get an idea of receiving the AVRO messages ✌️

**Comment by nirmalchandra** [comment]
Can you put the ticks against the [CHECKLIST(click)](https://github.com/authorjapps/zerocode/pull/490#issue-627889768) above?

**Comment by M3lkior** [comment]
> Can you please add an(or couple of) integration tests ?
> That will help all reviewers to get an idea of receiving the AVRO messages ✌️

yes, this is plan. This a Draft PR in order to add those tests

**Review by nirmalchandra — APPROVED** [review]

**Review by authorjapps — APPROVED** [review]

**Pull request merged**
